server:
  port: 8080
  
spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 50MB
  application:
    name: JODConverter Sample Rest Api

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003,2004,2005
    format-options:
      html:
        store:
          TEXT:
            FilterOptions: EmbedImages

      xhtml:
        store:
          TEXT:
            FilterOptions: EmbedImages

logging:
  level:
    org.jodconverter: info
